import type { Card, AIDeckType } from "./types"

// Krenko Goblins - Aggressive goblin tribal
export const krenkoGoblinsDeck: Card[] = [
  {
    id: "krenko",
    name: "Krenko, Mob Boss",
    manaCost: "{2}{R}{R}",
    cmc: 4,
    type: "creature",
    subtype: "Goblin Warrior",
    text: "{T}: Create X 1/1 red Goblin creature tokens, where X is the number of Goblins you control.",
    power: 3,
    toughness: 3,
    colors: ["R"],
    isCommander: true,
  },
  ...Array.from({ length: 4 }, (_, i) => ({
    id: `goblin-lackey-${i}`,
    name: "Goblin Lackey",
    manaCost: "{R}",
    cmc: 1,
    type: "creature" as const,
    subtype: "Goblin",
    text: "Whenever Goblin Lackey deals damage to a player, you may put a Goblin permanent card from your hand onto the battlefield.",
    power: 1,
    toughness: 1,
    colors: ["R" as const],
  })),
  ...Array.from({ length: 4 }, (_, i) => ({
    id: `goblin-piker-${i}`,
    name: "Goblin Piker",
    manaCost: "{1}{R}",
    cmc: 2,
    type: "creature" as const,
    subtype: "Goblin Warrior",
    text: "",
    power: 2,
    toughness: 1,
    colors: ["R" as const],
  })),
  ...Array.from({ length: 3 }, (_, i) => ({
    id: `goblin-warchief-${i}`,
    name: "Goblin Warchief",
    manaCost: "{1}{R}{R}",
    cmc: 3,
    type: "creature" as const,
    subtype: "Goblin Warrior",
    text: "Goblin spells you cast cost {1} less to cast. Goblins you control have haste.",
    power: 2,
    toughness: 2,
    colors: ["R" as const],
  })),
  ...Array.from({ length: 3 }, (_, i) => ({
    id: `goblin-chieftain-${i}`,
    name: "Goblin Chieftain",
    manaCost: "{1}{R}{R}",
    cmc: 3,
    type: "creature" as const,
    subtype: "Goblin",
    text: "Haste. Other Goblin creatures you control get +1/+1 and have haste.",
    power: 2,
    toughness: 2,
    colors: ["R" as const],
  })),
  ...Array.from({ length: 2 }, (_, i) => ({
    id: `siege-gang-${i}`,
    name: "Siege-Gang Commander",
    manaCost: "{3}{R}{R}",
    cmc: 5,
    type: "creature" as const,
    subtype: "Goblin",
    text: "When Siege-Gang Commander enters the battlefield, create three 1/1 red Goblin creature tokens. {1}{R}, Sacrifice a Goblin: Siege-Gang Commander deals 2 damage to any target.",
    power: 2,
    toughness: 2,
    colors: ["R" as const],
  })),
  {
    id: "goblin-king",
    name: "Goblin King",
    manaCost: "{1}{R}{R}",
    cmc: 3,
    type: "creature",
    subtype: "Goblin",
    text: "Other Goblin creatures get +1/+1 and have mountainwalk.",
    power: 2,
    toughness: 2,
    colors: ["R"],
  },
  ...Array.from({ length: 3 }, (_, i) => ({
    id: `lightning-bolt-${i}`,
    name: "Lightning Bolt",
    manaCost: "{R}",
    cmc: 1,
    type: "instant" as const,
    text: "Lightning Bolt deals 3 damage to any target.",
    colors: ["R" as const],
  })),
  {
    id: "goblin-bombardment",
    name: "Goblin Bombardment",
    manaCost: "{1}{R}",
    cmc: 2,
    type: "enchantment",
    text: "Sacrifice a creature: Goblin Bombardment deals 1 damage to any target.",
    colors: ["R"],
  },
  {
    id: "sol-ring-ai",
    name: "Sol Ring",
    manaCost: "{1}",
    cmc: 1,
    type: "artifact",
    text: "{T}: Add {C}{C}.",
    colors: ["C"],
  },
  ...Array.from({ length: 18 }, (_, i) => ({
    id: `mountain-krenko-${i}`,
    name: "Mountain",
    manaCost: "",
    cmc: 0,
    type: "land" as const,
    text: "{T}: Add {R}.",
    colors: ["R" as const],
  })),
]

// Talrand Control - Counterspells and drakes
export const talrandControlDeck: Card[] = [
  {
    id: "talrand",
    name: "Talrand, Sky Summoner",
    manaCost: "{2}{U}{U}",
    cmc: 4,
    type: "creature",
    subtype: "Merfolk Wizard",
    text: "Whenever you cast an instant or sorcery spell, create a 2/2 blue Drake creature token with flying.",
    power: 2,
    toughness: 2,
    colors: ["U"],
    isCommander: true,
  },
  ...Array.from({ length: 4 }, (_, i) => ({
    id: `counterspell-${i}`,
    name: "Counterspell",
    manaCost: "{U}{U}",
    cmc: 2,
    type: "instant" as const,
    text: "Counter target spell.",
    colors: ["U" as const],
  })),
  ...Array.from({ length: 3 }, (_, i) => ({
    id: `mana-leak-${i}`,
    name: "Mana Leak",
    manaCost: "{1}{U}",
    cmc: 2,
    type: "instant" as const,
    text: "Counter target spell unless its controller pays {3}.",
    colors: ["U" as const],
  })),
  ...Array.from({ length: 3 }, (_, i) => ({
    id: `negate-${i}`,
    name: "Negate",
    manaCost: "{1}{U}",
    cmc: 2,
    type: "instant" as const,
    text: "Counter target noncreature spell.",
    colors: ["U" as const],
  })),
  ...Array.from({ length: 3 }, (_, i) => ({
    id: `ponder-${i}`,
    name: "Ponder",
    manaCost: "{U}",
    cmc: 1,
    type: "sorcery" as const,
    text: "Look at the top three cards of your library, then put them back in any order. You may shuffle. Draw a card.",
    colors: ["U" as const],
  })),
  ...Array.from({ length: 3 }, (_, i) => ({
    id: `preordain-${i}`,
    name: "Preordain",
    manaCost: "{U}",
    cmc: 1,
    type: "sorcery" as const,
    text: "Scry 2, then draw a card.",
    colors: ["U" as const],
  })),
  {
    id: "cyclonic-rift",
    name: "Cyclonic Rift",
    manaCost: "{1}{U}",
    cmc: 2,
    type: "instant",
    text: "Return target nonland permanent you don't control to its owner's hand. Overload {6}{U}",
    colors: ["U"],
  },
  {
    id: "aetherize",
    name: "Aetherize",
    manaCost: "{3}{U}",
    cmc: 4,
    type: "instant",
    text: "Return all attacking creatures to their owner's hand.",
    colors: ["U"],
  },
  ...Array.from({ length: 2 }, (_, i) => ({
    id: `snapcaster-${i}`,
    name: "Snapcaster Mage",
    manaCost: "{1}{U}",
    cmc: 2,
    type: "creature" as const,
    subtype: "Human Wizard",
    text: "Flash. When Snapcaster Mage enters the battlefield, target instant or sorcery card in your graveyard gains flashback until end of turn.",
    power: 2,
    toughness: 1,
    colors: ["U" as const],
  })),
  {
    id: "sol-ring-talrand",
    name: "Sol Ring",
    manaCost: "{1}",
    cmc: 1,
    type: "artifact",
    text: "{T}: Add {C}{C}.",
    colors: ["C"],
  },
  ...Array.from({ length: 20 }, (_, i) => ({
    id: `island-talrand-${i}`,
    name: "Island",
    manaCost: "",
    cmc: 0,
    type: "land" as const,
    text: "{T}: Add {U}.",
    colors: ["U" as const],
  })),
]

// Omnath Landfall - Land-based ramp
export const omnathLandfallDeck: Card[] = [
  {
    id: "omnath",
    name: "Omnath, Locus of Rage",
    manaCost: "{3}{R}{R}{G}{G}",
    cmc: 7,
    type: "creature",
    subtype: "Elemental",
    text: "Landfall - Whenever a land enters the battlefield under your control, create a 5/5 red and green Elemental creature token. Whenever Omnath or another Elemental you control dies, Omnath deals 3 damage to any target.",
    power: 5,
    toughness: 5,
    colors: ["R", "G"],
    isCommander: true,
  },
  ...Array.from({ length: 4 }, (_, i) => ({
    id: `sakura-tribe-${i}`,
    name: "Sakura-Tribe Elder",
    manaCost: "{1}{G}",
    cmc: 2,
    type: "creature" as const,
    subtype: "Snake Shaman",
    text: "Sacrifice Sakura-Tribe Elder: Search your library for a basic land card, put that card onto the battlefield tapped, then shuffle.",
    power: 1,
    toughness: 1,
    colors: ["G" as const],
  })),
  ...Array.from({ length: 3 }, (_, i) => ({
    id: `cultivate-omnath-${i}`,
    name: "Cultivate",
    manaCost: "{2}{G}",
    cmc: 3,
    type: "sorcery" as const,
    text: "Search your library for up to two basic land cards, reveal those cards, put one onto the battlefield tapped and the other into your hand, then shuffle.",
    colors: ["G" as const],
  })),
  ...Array.from({ length: 3 }, (_, i) => ({
    id: `explosive-veg-${i}`,
    name: "Explosive Vegetation",
    manaCost: "{3}{G}",
    cmc: 4,
    type: "sorcery" as const,
    text: "Search your library for up to two basic land cards, put them onto the battlefield tapped, then shuffle.",
    colors: ["G" as const],
  })),
  {
    id: "avenger-of-zendikar",
    name: "Avenger of Zendikar",
    manaCost: "{5}{G}{G}",
    cmc: 7,
    type: "creature",
    subtype: "Elemental",
    text: "When Avenger of Zendikar enters the battlefield, create a 0/1 green Plant creature token for each land you control. Landfall - Whenever a land enters the battlefield under your control, you may put a +1/+1 counter on each Plant creature you control.",
    power: 5,
    toughness: 5,
    colors: ["G"],
  },
  {
    id: "lotus-cobra",
    name: "Lotus Cobra",
    manaCost: "{1}{G}",
    cmc: 2,
    type: "creature",
    subtype: "Snake",
    text: "Landfall - Whenever a land enters the battlefield under your control, add one mana of any color.",
    power: 2,
    toughness: 1,
    colors: ["G"],
  },
  {
    id: "sol-ring-omnath",
    name: "Sol Ring",
    manaCost: "{1}",
    cmc: 1,
    type: "artifact",
    text: "{T}: Add {C}{C}.",
    colors: ["C"],
  },
  ...Array.from({ length: 10 }, (_, i) => ({
    id: `forest-omnath-${i}`,
    name: "Forest",
    manaCost: "",
    cmc: 0,
    type: "land" as const,
    text: "{T}: Add {G}.",
    colors: ["G" as const],
  })),
  ...Array.from({ length: 10 }, (_, i) => ({
    id: `mountain-omnath-${i}`,
    name: "Mountain",
    manaCost: "",
    cmc: 0,
    type: "land" as const,
    text: "{T}: Add {R}.",
    colors: ["R" as const],
  })),
]

// Edgar Vampires - Aggressive vampire tribal
export const edgarVampiresDeck: Card[] = [
  {
    id: "edgar-markov",
    name: "Edgar Markov",
    manaCost: "{3}{R}{W}{B}",
    cmc: 6,
    type: "creature",
    subtype: "Vampire Knight",
    text: "Eminence - Whenever you cast another Vampire spell, if Edgar Markov is in the command zone or on the battlefield, create a 1/1 black Vampire creature token. First strike, haste. Whenever Edgar Markov attacks, put a +1/+1 counter on each Vampire you control.",
    power: 4,
    toughness: 4,
    colors: ["W", "B", "R"],
    isCommander: true,
  },
  ...Array.from({ length: 4 }, (_, i) => ({
    id: `vampire-nighthawk-${i}`,
    name: "Vampire Nighthawk",
    manaCost: "{1}{B}{B}",
    cmc: 3,
    type: "creature" as const,
    subtype: "Vampire Shaman",
    text: "Flying, deathtouch, lifelink",
    power: 2,
    toughness: 3,
    colors: ["B" as const],
  })),
  ...Array.from({ length: 4 }, (_, i) => ({
    id: `blood-artist-${i}`,
    name: "Blood Artist",
    manaCost: "{1}{B}",
    cmc: 2,
    type: "creature" as const,
    subtype: "Vampire",
    text: "Whenever Blood Artist or another creature dies, target player loses 1 life and you gain 1 life.",
    power: 0,
    toughness: 1,
    colors: ["B" as const],
  })),
  ...Array.from({ length: 3 }, (_, i) => ({
    id: `legion-lieutenant-${i}`,
    name: "Legion Lieutenant",
    manaCost: "{W}{B}",
    cmc: 2,
    type: "creature" as const,
    subtype: "Vampire Knight",
    text: "Other Vampires you control get +1/+1.",
    power: 2,
    toughness: 2,
    colors: ["W" as const, "B" as const],
  })),
  {
    id: "captivating-vampire",
    name: "Captivating Vampire",
    manaCost: "{1}{B}{B}",
    cmc: 3,
    type: "creature",
    subtype: "Vampire",
    text: "Other Vampire creatures you control get +1/+1. Tap five untapped Vampires you control: Gain control of target creature. It becomes a Vampire in addition to its other types.",
    power: 2,
    toughness: 2,
    colors: ["B"],
  },
  ...Array.from({ length: 2 }, (_, i) => ({
    id: `terminate-${i}`,
    name: "Terminate",
    manaCost: "{B}{R}",
    cmc: 2,
    type: "instant" as const,
    text: "Destroy target creature. It can't be regenerated.",
    colors: ["B" as const, "R" as const],
  })),
  {
    id: "sol-ring-edgar",
    name: "Sol Ring",
    manaCost: "{1}",
    cmc: 1,
    type: "artifact",
    text: "{T}: Add {C}{C}.",
    colors: ["C"],
  },
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `swamp-edgar-${i}`,
    name: "Swamp",
    manaCost: "",
    cmc: 0,
    type: "land" as const,
    text: "{T}: Add {B}.",
    colors: ["B" as const],
  })),
  ...Array.from({ length: 5 }, (_, i) => ({
    id: `plains-edgar-${i}`,
    name: "Plains",
    manaCost: "",
    cmc: 0,
    type: "land" as const,
    text: "{T}: Add {W}.",
    colors: ["W" as const],
  })),
  ...Array.from({ length: 5 }, (_, i) => ({
    id: `mountain-edgar-${i}`,
    name: "Mountain",
    manaCost: "",
    cmc: 0,
    type: "land" as const,
    text: "{T}: Add {R}.",
    colors: ["R" as const],
  })),
]

export function getAIDeck(deckType: AIDeckType): Card[] {
  switch (deckType) {
    case "krenko_goblins":
      return krenkoGoblinsDeck
    case "talrand_control":
      return talrandControlDeck
    case "omnath_landfall":
      return omnathLandfallDeck
    case "edgar_vampires":
      return edgarVampiresDeck
    default:
      return krenkoGoblinsDeck
  }
}

export const AI_DECK_INFO: Record<AIDeckType, { name: string; description: string; color: string }> = {
  krenko_goblins: {
    name: "Krenko Goblins",
    description: "Aggro - Abruma con tokens de goblins",
    color: "bg-red-500",
  },
  talrand_control: {
    name: "Talrand Control",
    description: "Control - Counterspells y drakes voladores",
    color: "bg-blue-500",
  },
  omnath_landfall: {
    name: "Omnath Landfall",
    description: "Ramp - Elementales gigantes por landfall",
    color: "bg-gradient-to-r from-red-500 to-green-500",
  },
  edgar_vampires: {
    name: "Edgar Vampires",
    description: "Aggro tribal - Vampiros con lifelink",
    color: "bg-gradient-to-r from-red-500 via-gray-800 to-amber-200",
  },
}
