import type { Card } from "./types"

// Sample Blight Curse themed deck - Black/Green commander deck focused on -1/-1 counters and curses
export const blightCurseDeck: Card[] = [
  // Commander
  {
    id: "hapatra",
    name: "Hapatra, Vizier of Poisons",
    manaCost: "{B}{G}",
    cmc: 2,
    type: "creature",
    subtype: "Human Cleric",
    text: "Whenever Hapatra deals combat damage to a player, you may put a -1/-1 counter on target creature. Whenever you put one or more -1/-1 counters on a creature, create a 1/1 green Snake token with deathtouch.",
    power: 2,
    toughness: 2,
    colors: ["B", "G"],
    isCommander: true,
  },
  // Creatures
  {
    id: "plague-stinger",
    name: "Plague Stinger",
    manaCost: "{1}{B}",
    cmc: 2,
    type: "creature",
    subtype: "Insect Horror",
    text: "Flying, infect",
    power: 1,
    toughness: 1,
    colors: ["B"],
  },
  {
    id: "ichor-rats",
    name: "Ichor Rats",
    manaCost: "{1}{B}{B}",
    cmc: 3,
    type: "creature",
    subtype: "Phyrexian Rat",
    text: "Infect. When Ichor Rats enters the battlefield, each player gets a poison counter.",
    power: 2,
    toughness: 1,
    colors: ["B"],
  },
  {
    id: "blight-mamba",
    name: "Blight Mamba",
    manaCost: "{1}{G}",
    cmc: 2,
    type: "creature",
    subtype: "Phyrexian Snake",
    text: "Infect. {1}{G}: Regenerate Blight Mamba.",
    power: 1,
    toughness: 1,
    colors: ["G"],
  },
  {
    id: "rot-wolf",
    name: "Rot Wolf",
    manaCost: "{2}{G}",
    cmc: 3,
    type: "creature",
    subtype: "Phyrexian Wolf",
    text: "Infect. Whenever a creature dealt damage by Rot Wolf this turn dies, you may draw a card.",
    power: 2,
    toughness: 2,
    colors: ["G"],
  },
  {
    id: "phyrexian-hydra",
    name: "Phyrexian Hydra",
    manaCost: "{3}{G}{G}",
    cmc: 5,
    type: "creature",
    subtype: "Phyrexian Hydra",
    text: "Infect, trample. If damage would be dealt to Phyrexian Hydra, prevent that damage. Put a -1/-1 counter on Phyrexian Hydra for each 1 damage prevented this way.",
    power: 7,
    toughness: 7,
    colors: ["G"],
  },
  {
    id: "midnight-banshee",
    name: "Midnight Banshee",
    manaCost: "{3}{B}{B}{B}",
    cmc: 6,
    type: "creature",
    subtype: "Spirit",
    text: "Wither. At the beginning of your upkeep, put a -1/-1 counter on each nonblack creature.",
    power: 5,
    toughness: 5,
    colors: ["B"],
  },
  {
    id: "devoted-druid",
    name: "Devoted Druid",
    manaCost: "{1}{G}",
    cmc: 2,
    type: "creature",
    subtype: "Elf Druid",
    text: "{T}: Add {G}. Put a -1/-1 counter on Devoted Druid: Untap Devoted Druid.",
    power: 0,
    toughness: 2,
    colors: ["G"],
  },
  {
    id: "nether-traitor",
    name: "Nether Traitor",
    manaCost: "{B}{B}",
    cmc: 2,
    type: "creature",
    subtype: "Spirit",
    text: "Haste, shadow. Whenever another creature is put into your graveyard from the battlefield, you may pay {B}. If you do, return Nether Traitor from your graveyard to the battlefield.",
    power: 1,
    toughness: 1,
    colors: ["B"],
  },
  {
    id: "sakura-tribe-elder",
    name: "Sakura-Tribe Elder",
    manaCost: "{1}{G}",
    cmc: 2,
    type: "creature",
    subtype: "Snake Shaman",
    text: "Sacrifice Sakura-Tribe Elder: Search your library for a basic land card, put that card onto the battlefield tapped, then shuffle.",
    power: 1,
    toughness: 1,
    colors: ["G"],
  },
  // Enchantments / Curses
  {
    id: "curse-of-deaths-hold",
    name: "Curse of Death's Hold",
    manaCost: "{3}{B}{B}",
    cmc: 5,
    type: "enchantment",
    subtype: "Aura Curse",
    text: "Enchant player. Creatures enchanted player controls get -1/-1.",
    colors: ["B"],
  },
  {
    id: "blowfly-infestation",
    name: "Blowfly Infestation",
    manaCost: "{2}{B}",
    cmc: 3,
    type: "enchantment",
    text: "Whenever a creature dies, if it had a -1/-1 counter on it, put a -1/-1 counter on target creature.",
    colors: ["B"],
  },
  {
    id: "nest-of-scarabs",
    name: "Nest of Scarabs",
    manaCost: "{2}{B}",
    cmc: 3,
    type: "enchantment",
    text: "Whenever you put one or more -1/-1 counters on a creature, create that many 1/1 black Insect creature tokens.",
    colors: ["B"],
  },
  {
    id: "parallel-lives",
    name: "Parallel Lives",
    manaCost: "{3}{G}",
    cmc: 4,
    type: "enchantment",
    text: "If an effect would create one or more tokens under your control, it creates twice that many of those tokens instead.",
    colors: ["G"],
  },
  // Instants
  {
    id: "tragic-slip",
    name: "Tragic Slip",
    manaCost: "{B}",
    cmc: 1,
    type: "instant",
    text: "Target creature gets -1/-1 until end of turn. Morbid — That creature gets -13/-13 until end of turn instead if a creature died this turn.",
    colors: ["B"],
  },
  {
    id: "putrefy",
    name: "Putrefy",
    manaCost: "{1}{B}{G}",
    cmc: 3,
    type: "instant",
    text: "Destroy target artifact or creature. It can't be regenerated.",
    colors: ["B", "G"],
  },
  {
    id: "golgari-charm",
    name: "Golgari Charm",
    manaCost: "{B}{G}",
    cmc: 2,
    type: "instant",
    text: "Choose one — All creatures get -1/-1 until end of turn; or destroy target enchantment; or regenerate each creature you control.",
    colors: ["B", "G"],
  },
  {
    id: "heroic-intervention",
    name: "Heroic Intervention",
    manaCost: "{1}{G}",
    cmc: 2,
    type: "instant",
    text: "Permanents you control gain hexproof and indestructible until end of turn.",
    colors: ["G"],
  },
  // Sorceries
  {
    id: "spread-the-sickness",
    name: "Spread the Sickness",
    manaCost: "{4}{B}",
    cmc: 5,
    type: "sorcery",
    text: "Destroy target creature, then proliferate.",
    colors: ["B"],
  },
  {
    id: "cultivate",
    name: "Cultivate",
    manaCost: "{2}{G}",
    cmc: 3,
    type: "sorcery",
    text: "Search your library for up to two basic land cards, reveal those cards, put one onto the battlefield tapped and the other into your hand, then shuffle.",
    colors: ["G"],
  },
  {
    id: "kodamas-reach",
    name: "Kodama's Reach",
    manaCost: "{2}{G}",
    cmc: 3,
    type: "sorcery",
    text: "Search your library for up to two basic land cards, reveal those cards, put one onto the battlefield tapped and the other into your hand, then shuffle.",
    colors: ["G"],
  },
  {
    id: "painful-truths",
    name: "Painful Truths",
    manaCost: "{2}{B}",
    cmc: 3,
    type: "sorcery",
    text: "Converge — You draw X cards and lose X life, where X is the number of colors of mana spent to cast this spell.",
    colors: ["B"],
  },
  // Artifacts
  {
    id: "sol-ring",
    name: "Sol Ring",
    manaCost: "{1}",
    cmc: 1,
    type: "artifact",
    text: "{T}: Add {C}{C}.",
    colors: ["C"],
  },
  {
    id: "golgari-signet",
    name: "Golgari Signet",
    manaCost: "{2}",
    cmc: 2,
    type: "artifact",
    text: "{1}, {T}: Add {B}{G}.",
    colors: ["C"],
  },
  {
    id: "contagion-clasp",
    name: "Contagion Clasp",
    manaCost: "{2}",
    cmc: 2,
    type: "artifact",
    text: "When Contagion Clasp enters the battlefield, put a -1/-1 counter on target creature. {4}, {T}: Proliferate.",
    colors: ["C"],
  },
  // Lands (simplified, would normally have 35-38)
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `swamp-${i + 1}`,
    name: "Swamp",
    manaCost: "",
    cmc: 0,
    type: "land" as const,
    text: "{T}: Add {B}.",
    colors: ["B" as const],
  })),
  ...Array.from({ length: 8 }, (_, i) => ({
    id: `forest-${i + 1}`,
    name: "Forest",
    manaCost: "",
    cmc: 0,
    type: "land" as const,
    text: "{T}: Add {G}.",
    colors: ["G" as const],
  })),
  {
    id: "overgrown-tomb",
    name: "Overgrown Tomb",
    manaCost: "",
    cmc: 0,
    type: "land",
    subtype: "Swamp Forest",
    text: "({T}: Add {B} or {G}.) As Overgrown Tomb enters the battlefield, you may pay 2 life. If you don't, it enters the battlefield tapped.",
    colors: ["B", "G"],
  },
  {
    id: "woodland-cemetery",
    name: "Woodland Cemetery",
    manaCost: "",
    cmc: 0,
    type: "land",
    text: "Woodland Cemetery enters the battlefield tapped unless you control a Swamp or a Forest. {T}: Add {B} or {G}.",
    colors: ["B", "G"],
  },
  {
    id: "golgari-rot-farm",
    name: "Golgari Rot Farm",
    manaCost: "",
    cmc: 0,
    type: "land",
    text: "Golgari Rot Farm enters the battlefield tapped. When it enters, return a land you control to its owner's hand. {T}: Add {B}{G}.",
    colors: ["B", "G"],
  },
  {
    id: "command-tower",
    name: "Command Tower",
    manaCost: "",
    cmc: 0,
    type: "land",
    text: "{T}: Add one mana of any color in your commander's color identity.",
    colors: ["C"],
  },
  {
    id: "evolving-wilds",
    name: "Evolving Wilds",
    manaCost: "",
    cmc: 0,
    type: "land",
    text: "{T}, Sacrifice this land: Search your library for a basic land card, put it onto the battlefield tapped, then shuffle.",
    colors: ["C"],
  },
  {
    id: "terramorphic-expanse",
    name: "Terramorphic Expanse",
    manaCost: "",
    cmc: 0,
    type: "land",
    text: "{T}, Sacrifice this land: Search your library for a basic land card, put it onto the battlefield tapped, then shuffle.",
    colors: ["C"],
  },
]

// Simple AI opponent deck (simplified)
export const aiOpponentDeck: Card[] = [
  {
    id: "ai-commander",
    name: "Krenko, Mob Boss",
    manaCost: "{2}{R}{R}",
    cmc: 4,
    type: "creature",
    subtype: "Goblin Warrior",
    text: "{T}: Create X 1/1 red Goblin creature tokens, where X is the number of Goblins you control.",
    power: 3,
    toughness: 3,
    colors: ["R"],
    isCommander: true,
  },
  ...Array.from({ length: 10 }, (_, i) => ({
    id: `goblin-${i + 1}`,
    name: "Goblin Piker",
    manaCost: "{1}{R}",
    cmc: 2,
    type: "creature" as const,
    subtype: "Goblin Warrior",
    text: "",
    power: 2,
    toughness: 1,
    colors: ["R" as const],
  })),
  ...Array.from({ length: 5 }, (_, i) => ({
    id: `goblin-chieftain-${i + 1}`,
    name: "Goblin Chieftain",
    manaCost: "{1}{R}{R}",
    cmc: 3,
    type: "creature" as const,
    subtype: "Goblin",
    text: "Haste. Other Goblin creatures you control get +1/+1 and have haste.",
    power: 2,
    toughness: 2,
    colors: ["R" as const],
  })),
  {
    id: "lightning-bolt",
    name: "Lightning Bolt",
    manaCost: "{R}",
    cmc: 1,
    type: "instant",
    text: "Lightning Bolt deals 3 damage to any target.",
    colors: ["R"],
  },
  ...Array.from({ length: 18 }, (_, i) => ({
    id: `mountain-${i + 1}`,
    name: "Mountain",
    manaCost: "",
    cmc: 0,
    type: "land" as const,
    text: "{T}: Add {R}.",
    colors: ["R" as const],
  })),
]
